### PR TITLE
Human injection, ansi terminal codes, command line, line feed

### PR DESCRIPTION
**Pull request by rickardnorlander**

### CODE REVIEW

**Comment by minimaxir** [comment]
GitHub is telling me that there's zero line change in the diff, yet the lines are clearly different. Does this break the file?

**Comment by Michagogo** [comment]
According to Github, this commit turns the file into a "binary file" that the web interface refuses to display.

**Comment by minimaxir** [comment]
Strings added in referenced commits.

**Comment by rickardnorlander** [comment]
I guess git auto detected the file as binary because there were too many unprintables.

**Comment by minimaxir** [comment]
It was because I added a null string in https://github.com/minimaxir/big-list-of-naughty-strings/commit/b518990120a10f0555fdad23444f1ebecbbd6968 (see #28 )

**Pull request closed without merging**
