### PR TITLE
Add ASCII bell (\u0007) character

### PR DESCRIPTION
**Pull request by romuald**
This character is outside of the valid characters for XML (and rejected by some parsers)

See https://www.w3.org/TR/REC-xml/#charsets

### CODE REVIEW

**Comment by minimaxir** [comment]
Where in the linked article does it discuss \u0007? I did a brief search (it's a long article) and did not see mention to that specific character.

**Comment by romuald** [comment]
The doc sates _#x9 | #xA | #xD | [#x20-#xD7FF] | [#xE000-#xFFFD] | [#x10000-#x10FFFF]_

So any character bellow \x09 isn't in the range

**Comment by zackw** [comment]
All of the C0 and C1 controls should really be represented in this file somewhere.

**Comment by severak** [comment]
Definitely needs some character outside of valid XML characters.

These can be met in wild, e.g. when pasting from some old word document.

**Comment by rohieb** [comment]
Note that the Bell character (^G) is already included [at the end of the file](https://github.com/minimaxir/big-list-of-naughty-strings/blob/673da19/blns.txt#L646):
```
The quic^H^H^H^H^H^Hk brown fo^G^G^G^G^G^G^G^G^G^G^Gx... [Beeeep]
```

**Comment by ssokolow** [comment]
> The doc sates valid characters are #x9 | #xA | #xD | [#x20-#xD7FF] | [#xE000-#xFFFD] | [#x10000-#x10FFFF]
> 
> So any character bellow \x09 isn't in the range

I prefer to use `\v` (`#xB`, vertical tab) and `\f` (`#xC`, form feed)  since, not only are they outside the valid ranges, they've got escapes which most common languages implement, so it's easy to mistakenly conclude that they *should* be valid and easy for someone to include in something you may encounter.

For example, to quote Eevee:
>All the way back in humble ASCII, U+000C FORM FEED can be used to encode a page break in plain text. veekun’s database uses form feeds to mark where the Pokédex flavor text in Gold, Silver, and Crystal breaks across two pages.
> -- https://eev.ee/blog/2015/09/12/dark-corners-of-unicode/

**Comment by micheal3466** [comment]
OK.... I need to follow this up. Many thanks

**Comment by micheal3466** [comment]
Ok

**Comment by awennimpagaritse1** [comment]
B2k

**Comment by ssokolow** [comment]
It looks like someone was stupid enough to think that hooking their spambot up to a GitHub account would be useful somehow.

**Comment by minimaxir** [comment]
Issue fixed. (TIL how blocking on GitHub works)

**Pull request merged**
