### PR TITLE
Added new iOS Crash String.

### PR DESCRIPTION
**Pull request by Plazmaz**
Added a string that crashes iOS when sent via text:
https://www.youtube.com/watch?v=G0iPhSuiMpk

### CODE REVIEW

**Comment by jude1924** [comment]
How do I get my pay?

**Comment by Plazmaz** [comment]
@jude1924 what?

**Comment by Plazmaz** [comment]
@jude1924 why would I give you bitcoin?

**Comment by jude1924** [comment]
All I'm asking is how do I get my money from airbitz

**Pull request merged**
