### PR TITLE
Regenerate resource.go

### LINKED ISSUE #187: Can't compile go code
Environment:

```
$ go version
go version go1.11.1 darwin/amd64
```

Steps to reproduce:

```
$ go get github.com/minimaxir/big-list-of-naughty-strings/...
# github.com/minimaxir/big-list-of-naughty-strings/naughtystrings/internal
github.com/minimaxir/big-list-of-naughty-strings/naughtystrings/internal/resource.go:830:102: invalid BOM in the middle of the file
github.com/minimaxir/big-list-of-naughty-strings/naughtystrings/internal/resource.go:831:4: invalid BOM in the middle of the file
github.com/minimaxir/big-list-of-naughty-strings/naughtystrings/internal/resource.go:876:23: invalid BOM in the middle of the file
```

### PR DESCRIPTION
**Pull request by dmolesUC**
Fixes #187 (AFAICT).

### CODE REVIEW

**Comment by paulfurley** [comment]
Thanks for this fix. We also encountered #187

**Comment by paulfurley** [comment]
Hmm it's hard to tell what's changed here due to all the whitespace changes :\

**Comment by dmolesUC3** [comment]
Sorry, the Go code generation tools use tabs by default (like most Go programmers). I'm not sure why it was indented with spaces to begin with.

You can see the diff ignoring whitespace changes if you [add `?w=1` to the URL](https://github.com/minimaxir/big-list-of-naughty-strings/pull/192/files?w=1) (and then click "Load Diff").

It looks like the most important changes in terms of #187 are around lines 830-831 (now 831-832, corresponding to lines [135](https://github.com/minimaxir/big-list-of-naughty-strings/blob/master/blns.txt#L135) and [139](https://github.com/minimaxir/big-list-of-naughty-strings/blob/master/blns.txt#L139)) and 876 (now 880, corresponding to line [241](https://github.com/minimaxir/big-list-of-naughty-strings/blob/master/blns.txt#L241)) where some byte order marks were escaped. (To be honest I'm not sure just why the code generator thinks there are byte order marks in that emoticon, but I think that could be filed as a separate issue.)

Apart from that, it just looks like there are some strings that have been added to the source files since the last time the Go files were regenerated.

**Comment by paulfurley** [comment]
Awesome. We've just generated our own too with github.com/go-bindata/go-bindata and it comes out basically identical to yours, so I'm confident this is right.

We've also added #193 to add a `Makefile` to save the next person some time :)

**Pull request merged**
