### PR TITLE
Add EICAR and GTUBE antivirus and antispam triggers

### PR DESCRIPTION
**Pull request by lamby**
Signed-off-by: Chris Lamb <chris@chris-lamb.co.uk>

### CODE REVIEW

**Comment by minimaxir** [comment]
For usability, we can't use the antivirus strings. I've added a note to the README reflecting this.

**Comment by Michagogo** [comment]
Why not? Having the strings in the middle of the file shouldn't cause detection, as far as I know. Unless I'm misremembering, the EICAR test is defined as a file with the specific contents, not just a string.

**Comment by lamby** [comment]
.. and GTUBE?

**Comment by Michagogo** [comment]
Not sure. Not very familiar with it. Also, may want to test with VirusTotal
or something, since I'm not sure if it's actually implemented properly
everywhere.

**Comment by minimaxir** [comment]
Since this project is so new, I am taking a more conservative approach toward potentially-breaking additions.

Both EICAR and GTUBE would need multiplatform testing to make sure `blns.txt` doesn't flag antivirus software. If they pass testing, they can be added, but that'll take time.

**Pull request closed without merging**
