### PR TITLE
Added 0xabad1dea Numeric String

### PR DESCRIPTION
**Pull request by 06b**
@0xabad1dea is known to break things with her name.

### CODE REVIEW

**Comment by minimaxir** [comment]
Hmm, why is the diff file appearing as binary., like with #21 ?

I may have to manually merge these PRs.

**Comment by 06b** [comment]
I don't know why github changed it to binary :/

**Comment by 0xabad1dea** [comment]
*sound of being unable to make this up*

**Comment by minimaxir** [comment]
Added in https://github.com/minimaxir/big-list-of-naughty-strings/commit/b021962ef57466cf741a35080167d9b1199cb889

Closing.

**Comment by egeste** [comment]
@0xabad1dea I was just reading through the text file, saw your name, blamed the file, found this PR, and came to congratulate you on your infamy.

**Pull request closed without merging**
